[package]
name = "usage-ui-iced-prototype"
version = "0.1.0"
edition = "2024"
publish = false

[dependencies]
async-channel = "2.5"
iced = { version = "0.14.0", default-features = false, features = ["advanced-shaping", "thread-pool", "tiny-skia"] }
tray-icon = { version = "0.25.1", default-features = false }
